### ISSUE TITLE
Can't compile CLI on RHEL8 Rust

### ISSUE THREAD

**Issue by s-andrews** [DesmondWillowbrook/Librarian-Server#4]
```
[andrewss@bioinform cli]$ cargo run --release -- 100000 ../frontend/example_inputs/in.fastq
error: failed to parse manifest at `/data/private/Librarian-Server/cli/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature

```

**Comment by DesmondWillowbrook** [comment]
What's your compiler version? (`cargo --version`)

**Comment by DesmondWillowbrook** [comment]
I've changed the edition requirement (we didn't need it anyway), so it should compile with older versions.

**Comment by DesmondWillowbrook** [comment]
I've changed the edition requirement (we didn't need it anyway), so it should compile with older versions.

**Comment by s-andrews** [comment]
Great, I'll give it another try.  For the record the compiler version on RHEL8 is ```cargo 1.54.0 (5ae8d74b3 2021-06-22)```
